# Generated by Django 4.0.3 on 2022-04-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='userId',
            new_name='user',
        ),
    ]
