# Generated by Django 4.0.3 on 2022-03-29 11:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='XHUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.IntegerField()),
                ('soldItem', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=100, max_digits=4)),
                ('status', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Deactivated'), (3, 'Restricted')], default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
