# Generated by Django 4.0.3 on 2022-04-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XHUser', '0002_xhuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xhuser',
            name='type',
        ),
    ]
