# Generated by Django 4.0.3 on 2022-04-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XHUser', '0004_xhuser_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xhuser',
            old_name='type',
            new_name='role',
        ),
    ]
