# Generated by Django 4.0.3 on 2022-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XHUser', '0005_rename_type_xhuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0),
        ),
    ]
