# Generated by Django 4.0.3 on 2022-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XHUser', '0006_alter_xhuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhuser',
            name='studentId',
            field=models.CharField(max_length=150),
        ),
    ]
