# Generated by Django 4.0.3 on 2022-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XHUser', '0007_alter_xhuser_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unver'), (1, 'Verified'), (2, 'Deactivated'), (3, 'Restricted')], default=0),
        ),
    ]
